use MilkTeaShop
go

insert into category values('Milk Tea')
insert into category values('Fruit Tea')
insert into category values('Poppings Yogurt Tea')
insert into category values('Rock Salt Cheese')
insert into category values('Toppings')
go

insert into food(name, category) values ('Royal', 1)
insert into food(name, category) values ('Wintermelon', 1)
insert into food(name, category) values ('Roasted', 1)
insert into food(name, category) values ('Hazelnut', 1)
insert into food(name, category) values ('Caramel', 1)
insert into food(name, category) values ('Almond', 1)
insert into food(name, category) values ('Vanilla', 1)
insert into food(name, category) values ('Taro', 1)
insert into food(name, category) values ('Chocolate', 1)
insert into food(name, category) values ('Mocha', 1)
insert into food(name, category) values ('Honeydew', 1)
insert into food(name, category) values ('Coffee', 1)
insert into food(name, category) values ('Strawberry', 1)
insert into food(name, category) values ('Peppermint', 1)
insert into food(name, category) values ('Mango', 1)
insert into food(name, category) values ('Banana', 1)
insert into food(name, category) values ('Coffee Caramel', 1)
insert into food(name, category) values ('Cookies & Cream', 1)
insert into food(name, category) values ('Mochaccino', 1)
insert into food(name, category) values ('Black Forest', 1)
insert into food(name, category) values ('Double Dutch', 1)
insert into food(name, category) values ('Choco Oats', 1)

insert into food(name, category) values ('Green Apple', 2)
insert into food(name, category) values ('Wintermelon', 2)
insert into food(name, category) values ('Peach', 2)
insert into food(name, category) values ('Strawberry', 2)
insert into food(name, category) values ('Lychee', 2)
insert into food(name, category) values ('Mango', 2)
insert into food(name, category) values ('Passionfruit', 2)
insert into food(name, category) values ('Peach Mango', 2)

insert into food(name, category) values ('Lychee', 3)
insert into food(name, category) values ('Strawberry', 3)
insert into food(name, category) values ('Mango', 3)

insert into food(name, category) values ('Chocolate', 4)
insert into food(name, category) values ('Coffee', 4)
insert into food(name, category) values ('Wintermelon', 4)
insert into food(name, category) values ('Taro', 4)
insert into food(name, category) values ('Caramel', 4)
insert into food(name, category) values ('Royal', 4)
insert into food(name, category) values ('Cookies & Cream', 4)
insert into food(name, category) values ('Mochaccino', 4)
insert into food(name, category) values ('Double Dutch', 4)

insert into food(name, category) values ('Tapioca Pearls', 5)
insert into food(name, category) values ('Nata De Coco', 5)
insert into food(name, category) values ('Egg Pudding', 5)
insert into food(name, category) values ('Caramel Konjac Jelly', 5)
insert into food(name, category) values ('Coffee Jelly', 5)
insert into food(name, category) values ('Grass Jelly', 5)
insert into food(name, category) values ('Hantien Jelly', 5)
go
